### ISSUE TITLE
Missing namespaces

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/cli#17]
Thanks for locking #16 before I could save...

This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Shorter version as I don't feel like rewriting the whole thing again...

currently missing namespacing:
- [x] Model name
- [x] table name
- [x] Migrations (`_table` migration tied into the above, of course)

**Comment by jlsjonas** [comment]
For some extra info: Laravel's `make:model` does seem to (mostly) [support this](https://laracasts.com/discuss/channels/general-discussion/artisan-makemodel-specify-the-directory-and-namespace?page=2) (namespaced table name would still have to be coded in manually; vs. added to the template); however the structure generator breaks on \'s instead of handling them (hence this request)

**Comment by aocneanu** [comment]
@jlsjonas do not upgrade yet, it's for v3.3.x

**Comment by jlsjonas** [comment]
Aha, guess I shouldn't do the 3.2.3 update today then 😬

We might want to take a look at a better way to separate versions better//use matching composer minor versions depending on release target everywhere?
