### ISSUE TITLE
Vue router

### ISSUE THREAD

**Issue by VadimsTalapins** [laravel-enso/cli#30]
bug 

### Prerequisites
[ * ] Are you running the latest version?
* [ * ] Are you reporting to the correct repository?
* [ * ] Did you check the documentation?
* [ * ] Did you perform a cursory search?

### Description
For example I have create 
1) Model: Apple
2) Permission Group: administration.apples
3) Menu: route: administration.apples.index

Before creating the structure all routes administration.* (users, groups ....) work normally.
After creating structure. administration route works only administration.apples.*, other routes doesn't work:

[vue-router] Route with name 'administration.users.index' does not exist.  and other administration.* is the same error. Other routes system and other work fine.

After creating structure /resources/js/routes:
administration.js
administration/apples.js
administration/apples/
show.js and others

**Comment by VadimsTalapins** [comment]
![router bug](https://user-images.githubusercontent.com/48283230/61464272-aaead180-a97e-11e9-9f5b-a617aca51a79.png)

**Comment by VadimsTalapins** [comment]
I have remove /resources/js/routes/administration.js
and /resources/js/routes/administration folder
And all routes comes back. This is some bug.
![bug vue route v2](https://user-images.githubusercontent.com/48283230/61464723-6dd30f00-a97f-11e9-86e3-196380c99d2d.png)

**Comment by aocneanu** [comment]
It's not really a bug, it's more of a documentation lack.

`administration` is an core permission group, so the corresponding routes are placed in [@enso-ui/ui](https://github.com/enso-ui/ui/tree/master/src/bulma/routes).

When you reuse this group locally, the cli by default generates all the group's necessary route files, and the local administration.js overwrites the core one. But you figured it out in the end ;)

I would appreciate if you could make a contribution to the docs and add this yourself, maybe in [this section](https://docs.laravel-enso.com/guide/development.html#using-the-cli)

**Comment by aocneanu** [comment]
We'll leave this open until you or someone else from the team will update the docs.

**Comment by VadimsTalapins** [comment]
Ok, I'll try to describe it in the documentation.

**Comment by itarafath** [comment]
@VadimsTalapins 
Can you describe the solution?
THanks.
